version: '2'
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=test
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
  web:
    image: node:6.9
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: npm run gulp
    ports:
      - "3000:3000"
    links:
      - mysql
