version: '2'
services:
  postgres:
    image: willaustin/postgres-parkfinder:1.0
    environment:
      - POSTGRES_PASSWORD=test
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    # expose:
      # - "5433"
  web:
    image: node:6.9
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
    ports:
      - "3000:3000"
    links:
      - postgres
    environment:
      - PGUSER=postgres
      - PGPASSWORD=test
      - PGHOST=postgres
    depends_on:
      - postgres
